---

author: "Shalini Rallapalli Venkata"
date: "March 19, 2019"
output: html_document
---

```{r}
#5. In Chapter 4, we used logistic regression to predict the probability of default using income and balance on the Default data set. We will now estimate the test error of this logistic regression model using the validation set approach. Do not forget to set a random seed before beginning your analysis.
library(ISLR)
summary(Default)


#(a) Fit a logistic regression model that uses income and balance to predict default. 
set.seed(1)
glm.fit = glm(default ~ income + balance, data = Default, family = binomial)
summary(glm.fit)
```

```{r}
#(b) Using the validation set approach, estimate the test error of this model. In order to do this, you must perform the following steps:
#i. Split the sample set into a training set and a validation set.
#ii. Fit a multiple logistic regression model using only the training observations. 
#iii. Obtain a prediction of default status for each individual in the validation set by computing the posterior probability of default for that individual, and classifying the individual to the default category if the posterior probability is greater than 0.5. 
#iv. Compute the validation set error, which is the fraction of the observations in the validation set that are misclassi???ed. 
reqfunc = function() {
    # i.
    train_data = sample(dim(Default)[1], dim(Default)[1]/2)
    # ii.
    glm_fit = glm(default ~ income + balance, data = Default, family = binomial, 
        subset = train_data)
    # iii.
    glm_pred = rep("No", dim(Default)[1]/2)
    glm_probs = predict(glm_fit, Default[-train_data, ], type = "response")
    glm_pred[glm_probs > 0.5] = "Yes"
    # iv.
    return(mean(glm_pred != Default[-train_data, ]$default))
}
reqfunc()
```

```{r}
#c) Repeat the process in (b) three times, using three di???erent splits of the observations into a training set and a validation set. Comment on the results obtained.

reqfunc()

reqfunc()

reqfunc()


#The average is around 2.6% test error rate

```

```{r}
#d) Now consider a logistic regression model that predicts the probability of default using income, balance, and a dummy variable for student. Estimate the test error for this model using the validation set approach. Comment on whether or not including a dummy variable for student leads to a reduction in the test error rate

train_dataset = sample(dim(Default)[1], dim(Default)[1]/2)
glm_fit1 = glm(default ~ income + balance + student, data = Default, family = binomial, 
    subset = train_dataset)
glm_pred1 = rep("No", dim(Default)[1]/2)
glm_probs1 = predict(glm_fit1, Default[-train_dataset, ], type = "response")
glm_pred1[glm_probs1 > 0.5] = "Yes"
mean(glm_pred1 != Default[-train_dataset, ]$default)

```
#2.88% test error rate. Including a dummy variable for student does not lead to a reduction in the test error rate
```{r}
#7. In Sections 5.3.2 and 5.3.3, we saw that the cv.glm() function can be used in order to compute the LOOCV test error estimate. Alternatively, one could compute those quantities using just the glm() and predict.glm() functions, and a for loop. You will now take this approach in order to compute the LOOCV error for a simple logistic regression model on the Weekly data set. Recall that in the context of classi???cation problems, the LOOCV error is given in (5.4).

library(ISLR)
summary(Weekly)

```

```{r}
#(a) Fit a logistic regression model that predicts Direction using Lag1 and Lag2.
set.seed(123)
glm_fit2 = glm(Direction ~ Lag1 + Lag2, data = Weekly, family = binomial)
summary(glm_fit2)
```

```{r}
#(b) Fit a logistic regression model that predicts Direction using Lag1 and Lag2 using all but the ???rst observation.
glm_fit3 = glm(Direction ~ Lag1 + Lag2, data = Weekly[-1, ], family = binomial)
summary(glm_fit3)

```
```{r}
#(c) Use the model from (b) to predict the direction of the ???rst observation. You can do this by predicting that the ???rst observation will go up if P(Direction="Up"|Lag1, Lag2) > 0.5. Was this observation correctly classi???ed?

predict.glm(glm_fit3, Weekly[1, ], type = "response") > 0.5

```
Prediction of first observation is UP and true direction is DOWN. Hence the observation is not correctly classified.
```{r}
#(d) Write a for loop from i = 1 toi = n, wheren is the number of observations in the data set, that performs each of the following steps:
#i. Fit a logistic regression model using all but the ith observation to predict Direction using Lag1 and Lag2. ii. Compute the posterior probability of the market moving up for the ith observation. iii. Use the posterior probability for the ith observation in order to predict whether or not the market moves up. iv. Determine whether or not an error was made in predicting the direction for the ith observation. If an error was made, then indicate this as a 1, and otherwise indicate it as a 0.

errors <- rep(0, dim(Weekly)[1])
for (i in 1:dim(Weekly)[1]) {
    glm_fit4<- glm(Direction ~ Lag1 + Lag2, data = Weekly[-i, ],  family = "binomial")
    pred1 <- predict.glm(glm_fit4, Weekly[i, ], type = "response") > 0.5
    true_dir <- Weekly[i, ]$Direction == "Up"
    if (pred1 != true_dir)
        errors[i] <- 1
}
sum(errors)


```
There are a total of 490 errors

```{r}
#(e) Take the average of the n numbers obtained in (d)iv in order to obtain the LOOCV estimate for the test error. Comment on the results.

mean(errors)
```
LOOCV estmate for the test error rate is 44.995%


